# Site settings
title: Gustavo Siqueira
description: 'Mobile & Python Developer'
url: '//gugsrs.github.io'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Gustavo Siqueira'
  email: rsiqueira.gustavo@gmail.com
  facebook_username: gugsrs
  github_username:  gugsrs
  linkedin_username:  gugsrs

theme:
  name: 'Jekyll-Uno'
  url: 'https://github.com/joshgerdes/jekyll-uno'

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
